version: 2.1

orbs:
  node-orb: uraway/node-orb@dev:74cacd47dfe9cf6522841c259c7642c0d88bf887

workflows:
  version: 2

  smoke_test:
    jobs:
      - node-orb/ci-yarn-upgrade

  nightly:
    triggers:
      - schedule:
          cron: "00 10 * * 5"
          filters:
            branches:
              only: master

    jobs:
      - node-orb/ci-yarn-upgrade
