version: 2.1

orbs:
  node-orb: uraway/node-orb@dev:7c8ce70042e38051e510edae2e39ba9d992633d6

workflows:
  version: 2

  smoke_test:
    jobs:
      - node-orb/ci-yarn-upgrade

  nightly:
    triggers:
      - schedule:
          cron: "00 10 * * 5"
          filters:
            branches:
              only: master

    jobs:
      - node-orb/ci-yarn-upgrade
