version: 2.1

orbs:
  node-orb: uraway/node-orb@dev:b1457f42346928e9362a6f3bbf3d99be928ae3dd

workflows:
  version: 2

  smoke_test:
    jobs:
      - node-orb/bundle-update-pr

  nightly:
    triggers:
      - schedule:
          cron: "00 10 * * 5"
          filters:
            branches:
              only: master

    jobs:
      - node-orb/bundle-update-pr
