version: 2.1

orbs:
  node-orb: uraway/node-orb@dev:46599fc45a63b00ce12ee54d934dc65c98260863

workflows:
  version: 2

  smoke_test:
    jobs:
      - node-orb/ci-yarn-upgrade

  nightly:
    triggers:
      - schedule:
          cron: "00 10 * * 5"
          filters:
            branches:
              only: master

    jobs:
      - node-orb/ci-yarn-upgrade
