version: 2.1

orbs:
  node-orb: uraway/node-orb@dev:7b9abc1b8cf1f0635a324ed5b1c402c3db6291f8

workflows:
  version: 2

  smoke_test:
    jobs:
      - node-orb/ci-yarn-upgrade

  nightly:
    triggers:
      - schedule:
          cron: "00 10 * * 5"
          filters:
            branches:
              only: master

    jobs:
      - node-orb/ci-yarn-upgrade
