version: 2.1

orbs:
  node-orb: uraway/node-orb@dev:9324e3f612342fbb7278e78f43c31e96e2cde842

workflows:
  version: 2

  smoke_test:
    jobs:
      - node-orb/ci-yarn-upgrade

  nightly:
    triggers:
      - schedule:
          cron: "00 10 * * 5"
          filters:
            branches:
              only: master

    jobs:
      - node-orb/ci-yarn-upgrade
